# Generated by Django 5.0.6 on 2024-05-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('matric_number', models.CharField(max_length=50, unique=True)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('result', models.FileField(upload_to='results/')),
                ('essay1', models.FileField(upload_to='essays/')),
                ('essay2', models.FileField(upload_to='essays/')),
                ('essay3', models.FileField(upload_to='essays/')),
            ],
        ),
    ]
